version: '3.7'

services:

  mariadb:
    image: mariadb:10.6.14
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - ./sql/mariadb.cnf:/etc/mysql/mariadb.conf.d/mariadb.cnf
      - ./sql/seed.sql:/docker-entrypoint-initdb.d/seed.sql
    ports:
      - "3306:3306"

  minio:
    image: minio/minio:RELEASE.2025-09-07T16-13-09Z
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio-data:/data

  createbuckets:
    image: minio/mc:RELEASE.2025-08-13T08-35-41Z
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      until mc alias set local http://minio:9000 ${MINIO_ROOT_USER} ${MINIO_ROOT_PASSWORD}; do
        echo 'waiting for minio'; sleep 1;
      done;
      mc mb --ignore-existing local/${PAIMON_BUCKET};
      mc anonymous set public local/${PAIMON_BUCKET};
      mc mb --ignore-existing local/${ICEBERG_BUCKET};
      mc anonymous set public local/${ICEBERG_BUCKET};
      echo 'buckets ${PAIMON_BUCKET} and ${ICEBERG_BUCKET} ready';
      "

  jobmanager:
    image: flink:1.17.1
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        s3.endpoint: ${S3_ENDPOINT}
        s3.access-key: ${MINIO_ROOT_USER}
        s3.secret-key: ${MINIO_ROOT_PASSWORD}
        s3.path.style.access: true
    ports:
      - "8081:8081"
    command: jobmanager
    depends_on:
      - minio
    volumes:
      - ./jars/flink-sql-connector-mysql-cdc-2.4.1.jar:/opt/flink/lib/flink-sql-connector-mysql-cdc-2.4.1.jar
      - ./jars/flink-connector-jdbc-3.1.0-1.17.jar:/opt/flink/lib/flink-connector-jdbc-3.1.0-1.17.jar
      - ./jars/paimon-flink-1.17-0.6-20231027.002013-49.jar:/opt/flink/lib/paimon-flink-1.17-0.6-20231027.002013-49.jar
      - ./jars/flink-shaded-hadoop-2-uber-2.8.3-10.0.jar:/opt/flink/lib/flink-shaded-hadoop-2-uber-2.8.3-10.0.jar
      - ./jars/flink-s3-fs-hadoop-1.17.1.jar:/opt/flink/plugins/s3-fs-hadoop/flink-s3-fs-hadoop-1.17.1.jar
      - ./jars/paimon-s3-0.6-20231027.002013-54.jar:/opt/flink/lib/paimon-s3-0.6-20231027.002013-54.jar
      - ./jobs:/opt/flink/jobs
    deploy:
          replicas: 1

  taskmanager:
    image: flink:1.17.1
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        s3.endpoint: ${S3_ENDPOINT}
        s3.access-key: ${MINIO_ROOT_USER}
        s3.secret-key: ${MINIO_ROOT_PASSWORD}
        s3.path.style.access: true
        taskmanager.numberOfTaskSlots: 2
    depends_on:
      - jobmanager
      - minio
    command: taskmanager
    volumes:
      - ./jars/flink-sql-connector-mysql-cdc-2.4.1.jar:/opt/flink/lib/flink-sql-connector-mysql-cdc-2.4.1.jar
      - ./jars/flink-connector-jdbc-3.1.0-1.17.jar:/opt/flink/lib/flink-connector-jdbc-3.1.0-1.17.jar
      - ./jars/paimon-flink-1.17-0.6-20231027.002013-49.jar:/opt/flink/lib/paimon-flink-1.17-0.6-20231027.002013-49.jar
      - ./jars/flink-shaded-hadoop-2-uber-2.8.3-10.0.jar:/opt/flink/lib/flink-shaded-hadoop-2-uber-2.8.3-10.0.jar
      - ./jars/flink-s3-fs-hadoop-1.17.1.jar:/opt/flink/plugins/s3-fs-hadoop/flink-s3-fs-hadoop-1.17.1.jar
      - ./jars/paimon-s3-0.6-20231027.002013-54.jar:/opt/flink/lib/paimon-s3-0.6-20231027.002013-54.jar
    deploy:
          replicas: 2

  seatunnel:
    build:
      context: ./seatunnel
    image: seatunnel:2.3.11
    container_name: seatunnel
    profiles: ["seatunnel"]
    volumes:
      - ./seatunnel:/config
    command: ["/opt/seatunnel/bin/seatunnel.sh", "--config", "/config/seatunnel.conf", "-m", "local"]

volumes:
  minio-data:
